# Generated by Django 6.0.3 on 2026-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
