# Generated by Django 5.2.8 on 2026-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_task_deleted_alter_expense_id_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
