# Generated by Django 6.0.3 on 2026-04-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
